###
@url=http://localhost:8081
@game=ticTacToe
@user_id=58300e77-3581-4fff-8fbb-943c2add0be1
@user_id2=dabd3e13-1f7b-4714-a2db-d3013a9a3498
@game_id=ad9b579c-ed22-4cf2-b886-d676892bbadf

### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### GET catalog
GET {{url}}/catalog

### GET game name
GET {{url}}/catalog/gameType/tictactoe
Language: EN


### POST new game
POST {{url}}/games
X-UserId: {{user_id}}
Content-Type: application/json

{
  "gameType": "tictactoe",
  "boardSize": 3,
  "playerCount": 2
}

### GET all game
GET {{url}}/games

### GET game by id
GET {{url}}/games/{{game_id}}

### GET game by status
GET {{url}}/games?status=ongoing

### GET stats
GET {{url}}/games/stats


### GET games by playerId
GET {{url}}/games
X-UserId: {{user_id}}

### GET possibles moves
GET {{url}}/games/{{game_id}}/moves


### PUT new move
PUT {{url}}/games/{{game_id}}/moves
X-UserId: {{user_id}}
Content-Type: application/json

{
  "x": 0,
  "y": 0
}