###
@url=http://localhost:8081
@game=ticTacToe
@user_id=c5f66c55-406e-43c5-9655-b7c5a91e90d7
@game_id=74f73279-eed6-4f08-8e1d-001496adccaf

### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### GET catalog
GET {{url}}/catalog

### POST new game
POST {{url}}/games
X-UserId: {{user_id}}
Content-Type: application/json

{
  "gameType": "tictactoe",
  "boardSize": 3,
  "playerCount": 2
}

### GET all game
GET {{url}}/games

### GET game by id
GET {{url}}/games/{{game_id}}

### GET game by status
GET {{url}}/games?status=ongoing


### GET games by playerId
GET {{url}}/games
X-UserId: {{user_id}}

### GET possibles moves
GET {{url}}/games/{{game_id}}/moves


### PUT new move
PUT {{url}}/games/{{game_id}}/moves
X-UserId: {{user_id}}
Content-Type: application/json

{
  "x": 1,
  "y": 2
}