###
@url=http://localhost:8081
@game=ticTacToe
@user_id=256eee58-a1bd-4ef4-80e9-79530b9b3fba
@user_id2=a2b082a0-30a9-4911-924c-c840443fdf9e
@game_id=26bfdb64-aff2-4e3e-8611-e91d97077956

### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### GET catalog
GET {{url}}/catalog

### POST new game
POST {{url}}/games
X-UserId: {{user_id}}
Content-Type: application/json

{
  "gameType": "tictactoe",
  "boardSize": 3,
  "playerCount": 2
}

### GET all game
GET {{url}}/games

### GET game by id
GET {{url}}/games/{{game_id}}

### GET game by status
GET {{url}}/games?status=ongoing


### GET games by playerId
GET {{url}}/games
X-UserId: {{user_id}}

### GET possibles moves
GET {{url}}/games/{{game_id}}/moves


### PUT new move
PUT {{url}}/games/{{game_id}}/moves
X-UserId: {{user_id}}
Content-Type: application/json

{
  "x": 0,
  "y": -1
}